---
version: 2.1

workflows:
  pre_commit:
    jobs:
      - run_pre_commit
  terraform_pipeline:
    jobs:
      - terraform_lint:
          context:
            - slack
      - run_terraform:
          requires:
            - terraform_lint
          context:
            - slack
            - gcp-dev
      - git_tag:
          context:
            - github-repo
            - slack
          requires:
            - run_terraform
          filters:
            branches:
              only:
                - master

orbs:
  slack: circleci/slack@4.1.3

jobs:
  run_pre_commit:
    docker:
      - image: quay.io/astronomer/ci-pre-commit:2021-01
    steps:
      - checkout
      - run: pre-commit run --all-files || { git --no-pager diff && false ; }

  terraform_lint:
    environment:
      TERRAFORM: terraform-0.12
    docker:
      - image: quay.io/astronomer/ci-terraform:2021-01
    steps:
      - checkout
      - run: pipeline/lint.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

  run_terraform:
    environment:
      TERRAFORM: terraform-0.12
    docker:
      - image: quay.io/astronomer/ci-terraform:2021-01
    steps:
      - checkout
      - run: EXAMPLE=from_scratch pipeline/run_terraform.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
      - run:
          command: echo DESTROY=1 EXAMPLE=from_scratch pipeline/run_terraform.sh
          when: always
      - slack/notify:
          event: fail
          template: basic_fail_1

  git_tag:
    docker:
      - image: quay.io/astronomer/ci-terraform:2021-01
    steps:
      - checkout
      - run: git remote set-url origin "https://astro-astronomer:${GITHUB_TOKEN}@github.com/astronomer/${CIRCLE_PROJECT_REPONAME}.git"
      - run: git tag 0.3.<< pipeline.number >>
      - run: git push origin << pipeline.git.branch >> --tags
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Release Successful! :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*:\n$(date --iso-8601=seconds)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*:\n0.3.<< pipeline.number >>"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
